[package]
name = "gallery"
version = "0.1.0"
authors = ["Vincent Kriek <vincent@kriek.org>"]

[dependencies]
quick-xml = "0.10.0"
rusqlite = "0.13.0"
rocket = "0.3.9"
rocket_codegen = "0.3.9"
libraw-sys = "0.1"
base64 = "0.9.1"
image = "0.19.0"
time = "0.1.40"
